from __future__ import annotations

import os
from pathlib import Path
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from .models import (
    AffordabilityResult,
    Listing,
    ListingDetailRequest,
    ListingDetailResponse,
    RealtorInfo,
    SavedListing,
    SavedListingCreate,
    SavedListingListResponse,
    SavedSearch,
    SavedSearchCreate,
    SavedSearchListResponse,
    SearchRequest,
    SearchResponse,
)
from .services.affordability import heuristic_affordability
from .services.apify_client import ApifyClient
from .services.direct_mls_client import DirectMLSClient
from .services.listings import ListingService
from .services.ollama_client import OllamaClient
from .services.scapling_client import ScaplingClient
from .services.saved_data import SavedDataStore

load_dotenv()

ROOT = Path(__file__).resolve().parents[1]
FRONTEND_DIR = ROOT / "frontend"
DATA_DIR = ROOT / "data"
RUNTIME_DIR = ROOT / "runtime-data"

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://host.docker.internal:11434").strip()
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:latest").strip()
SCAPLING_URL = os.getenv("SCAPLING_URL", "http://scapling-bridge:3000").strip()
SCAPLING_TOKEN = os.getenv("SCAPLING_TOKEN", "").strip()
FLARESOLVERR_URL = os.getenv("FLARESOLVERR_URL", "").strip()
MLS_API_URL = os.getenv("MLS_API_URL", "").strip()
MLS_API_TOKEN = os.getenv("MLS_API_TOKEN", "").strip()
APIFY_TOKEN = os.getenv("APIFY_TOKEN", "").strip()
APIFY_ACTOR = os.getenv("APIFY_ACTOR", "tri_angle/real-estate-aggregator").strip()
ENABLE_MOCK_FALLBACK = os.getenv("ENABLE_MOCK_FALLBACK", "false").lower() in {"1", "true", "yes"}

app = FastAPI(title="MLS Home Search Portal", version="1.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

ollama_client = OllamaClient(base_url=OLLAMA_URL, model=OLLAMA_MODEL)
scapling_client = ScaplingClient(
    base_url=SCAPLING_URL,
    token=SCAPLING_TOKEN or None,
    flaresolverr_url=FLARESOLVERR_URL or None,
)
direct_mls_client = DirectMLSClient(base_url=MLS_API_URL, token=MLS_API_TOKEN or None)
apify_client = ApifyClient(token=APIFY_TOKEN or None, actor=APIFY_ACTOR)
listing_service = ListingService(
    data_dir=DATA_DIR,
    scapling_client=scapling_client,
    direct_mls_client=direct_mls_client,
    apify_client=apify_client,
    enable_mock_fallback=ENABLE_MOCK_FALLBACK,
)
saved_data_store = SavedDataStore(db_path=RUNTIME_DIR / "portal.db")


def _heuristic_home_summary(home: Listing, effective_cap: int) -> tuple[str, bool, str]:
    pct = (home.price / effective_cap) if effective_cap else 1.0
    if pct <= 0.85:
        fit = True
        reason = "Comfortably below your effective cap."
    elif pct <= 1.0:
        fit = True
        reason = "Within budget, but tighter monthly flexibility."
    else:
        fit = False
        reason = "Over your effective budget cap."
    summary = (
        f"{home.address}: {home.beds if home.beds is not None else '?'} bd, "
        f"{home.baths if home.baths is not None else '?'} ba, "
        f"{home.sqft if home.sqft is not None else '?'} sqft."
    )
    return summary, fit, reason


@app.get("/health")
async def health() -> dict:
    return {
        "ok": True,
        "ollama_url": OLLAMA_URL,
        "scapling_url": SCAPLING_URL,
        "flaresolverr_configured": bool(FLARESOLVERR_URL),
        "mls_api_configured": bool(MLS_API_URL),
        "apify_configured": bool(APIFY_TOKEN),
        "mock_fallback_enabled": ENABLE_MOCK_FALLBACK,
    }


async def _run_search(req: SearchRequest) -> SearchResponse:
    profile = {
        "annual_income": req.annual_income,
        "monthly_debt": req.monthly_debt,
        "down_payment": req.down_payment,
        "interest_rate": req.interest_rate,
        "loan_term_years": req.loan_term_years,
        "requested_max_price": req.max_price,
        "area": req.area,
    }

    ai = await ollama_client.affordability_estimate(profile)
    notes: List[str] = []
    if ai is None:
        ai = heuristic_affordability(
            annual_income=req.annual_income,
            monthly_debt=req.monthly_debt,
            down_payment=req.down_payment,
            interest_rate=req.interest_rate,
            loan_term_years=req.loan_term_years,
        )
        notes.append("Ollama unavailable or returned invalid JSON. Used heuristic affordability model.")
    else:
        notes.append("Affordability generated by Ollama.")

    affordability = AffordabilityResult(**ai)
    effective_cap = min(req.max_price, affordability.max_affordable_home_price)

    raw_listings, listing_notes = await listing_service.search(req.area, effective_cap, req.provider)
    notes.extend(listing_notes)

    listings = [Listing(**l) for l in raw_listings if l.get("price", 10**9) <= effective_cap]
    if listings:
        sources = sorted({x.source for x in listings})
        notes.append(f"Listing sources: {', '.join(sources)}")

        analysis_input = {
            "area": req.area,
            "effective_cap": effective_cap,
            "affordability": affordability.model_dump(),
            "homes": [
                {
                    "id": h.id,
                    "address": h.address,
                    "city": h.city,
                    "state": h.state,
                    "price": h.price,
                    "beds": h.beds,
                    "baths": h.baths,
                    "sqft": h.sqft,
                }
                for h in listings[:8]
            ],
        }
        ai_summaries = await ollama_client.summarize_listings(analysis_input)
        if ai_summaries and isinstance(ai_summaries.get("homes"), list):
            by_id = {x.get("id"): x for x in ai_summaries["homes"] if isinstance(x, dict)}
            for h in listings:
                item = by_id.get(h.id)
                if not item:
                    summary, fit, reason = _heuristic_home_summary(h, effective_cap)
                    h.ai_summary = summary
                    h.ai_is_good_choice = fit
                    h.ai_reason = reason
                    continue
                h.ai_summary = item.get("summary") or None
                h.ai_is_good_choice = item.get("is_good_choice")
                h.ai_reason = item.get("reason") or None
            notes.append("AI listing summaries generated by Ollama.")
        else:
            for h in listings:
                summary, fit, reason = _heuristic_home_summary(h, effective_cap)
                h.ai_summary = summary
                h.ai_is_good_choice = fit
                h.ai_reason = reason
            notes.append("Listing summaries used heuristic fallback (Ollama summary unavailable).")
    else:
        notes.append("No listings found under effective budget cap.")

    return SearchResponse(
        area=req.area,
        requested_max_price=req.max_price,
        ai_affordability=affordability,
        effective_price_cap=effective_cap,
        listing_count=len(listings),
        listings=listings,
        notes=notes,
    )


@app.post("/api/search", response_model=SearchResponse)
async def search_homes(req: SearchRequest) -> SearchResponse:
    return await _run_search(req)


@app.post("/api/listing-details", response_model=ListingDetailResponse)
async def listing_details(req: ListingDetailRequest) -> ListingDetailResponse:
    details = await scapling_client.fetch_listing_details(req.listing_url)
    description = details.get("description")
    photos = details.get("photos") or []
    realtor = RealtorInfo(**(details.get("realtor") or {}))

    ai_payload = {
        "home": {
            "address": req.address,
            "city": req.city,
            "state": req.state,
            "price": req.price,
            "beds": req.beds,
            "baths": req.baths,
            "sqft": req.sqft,
            "description": description,
        },
        "budget_context": {
            "effective_price_cap": req.effective_price_cap,
            "monthly_payment_limit": req.monthly_payment_limit,
            "existing_reason": req.ai_reason,
        },
    }
    ai = await ollama_client.assess_listing_details(ai_payload)
    if ai is None:
        ai_is_good = req.price <= req.effective_price_cap
        ai_explanation = (
            "Price is within your effective cap, but review condition, taxes, and total payment."
            if ai_is_good
            else "Price is above your effective cap, so payment risk is likely high."
        )
    else:
        ai_is_good = ai.get("is_good_choice")
        ai_explanation = ai.get("explanation")

    if not realtor.broker_name and req.broker_name:
        realtor.broker_name = req.broker_name

    return ListingDetailResponse(
        listing_url=req.listing_url,
        description=description,
        photos=photos,
        realtor=realtor,
        ai_is_good_choice=ai_is_good,
        ai_explanation=ai_explanation,
    )


@app.get("/api/saved-searches", response_model=SavedSearchListResponse)
async def list_saved_searches() -> SavedSearchListResponse:
    return SavedSearchListResponse(items=saved_data_store.list_searches())


@app.post("/api/saved-searches", response_model=SavedSearch)
async def create_saved_search(req: SavedSearchCreate) -> SavedSearch:
    return saved_data_store.create_search(req)


@app.delete("/api/saved-searches/{search_id}")
async def delete_saved_search(search_id: int) -> dict:
    if not saved_data_store.delete_search(search_id):
        raise HTTPException(status_code=404, detail="Saved search not found")
    return {"ok": True}


@app.post("/api/saved-searches/{search_id}/run", response_model=SearchResponse)
async def run_saved_search(search_id: int) -> SearchResponse:
    saved = saved_data_store.get_search(search_id)
    if not saved:
        raise HTTPException(status_code=404, detail="Saved search not found")
    return await _run_search(saved.criteria)


@app.get("/api/saved-listings", response_model=SavedListingListResponse)
async def list_saved_listings() -> SavedListingListResponse:
    return SavedListingListResponse(items=saved_data_store.list_listings())


@app.post("/api/saved-listings", response_model=SavedListing)
async def create_saved_listing(req: SavedListingCreate) -> SavedListing:
    return saved_data_store.save_listing(req)


@app.delete("/api/saved-listings/{listing_id}")
async def delete_saved_listing(listing_id: int) -> dict:
    if not saved_data_store.delete_listing(listing_id):
        raise HTTPException(status_code=404, detail="Saved listing not found")
    return {"ok": True}


app.mount("/assets", StaticFiles(directory=FRONTEND_DIR), name="assets")


@app.get("/")
async def index() -> FileResponse:
    return FileResponse(FRONTEND_DIR / "index.html")
